### ISSUE TITLE
PackedSfen::init

### ISSUE THREAD

**Issue by bleu48** [TadaoYamaoka/cshogi#1]
PackedSfenはデフォルトで初期化されていないようですが
使ってないからですか？

**Comment by TadaoYamaoka** [comment]
ご指摘ありがとうございます。
確かに初期化が漏れていたため修正しました。
実装はしたもののテストしていなかったです。

**Comment by bleu48** [comment]
こちらこそ対応ありがとうございます。
割と初期から使ってたのですがmoveのビット配置とか違うので
両方同時に使わないように殺してるのかなぁと思って指摘しませんでした。
先週からdlshogi-zeroで遊んでて痺れ切らしました。
