### ISSUE TITLE
Boardをhashableに

### ISSUE THREAD

**Issue by bleu48** [TadaoYamaoka/cshogi#20]
BoardオブジェクトをbookKeyをhash値にしてhashableにするのは如何でしょうか？
ちょっとした差なのですが色々と簡便に書けるようになります。

**Comment by TadaoYamaoka** [comment]
デフォルトでインスタンごとにユニークなハッシュ値が生成されると思いますが、それではだめなのでしょうか？
```
board1 = Board()
print(hash(board1))
board2 = Board()
print(hash(board2))
```

Pythonのhashableは、インスタンスの生存期間中変わらない値である必要があるため、boardKeyは手を進めると値が変わってしまうため適切ではないかと思います。
局面を表すハッシュ値が欲しい場合は、明示的にboard.zobrist_hash()を使用する方が良いと思いますが、どうでしょうか。

**Comment by bleu48** [comment]
インスタンスの生存期間中変わらない値である必要があるのですね。
言語仕様に対する誤解がありました。すみません。
