### ISSUE TITLE
mate_move_in_1ply()について

### ISSUE THREAD

**Issue by Yasuyuki-Miura** [TadaoYamaoka/cshogi#21]
初めまして。私の環境だけかもしれませんが、念のため確認いただけると助かります。

mate_move_in_1ply()について、手番側に王手がかかっている場合でも詰めると判定しています
(合法手でない手を選択しているようです)

import cshogi
board = cshogi.Board('1+R6l/g2g2+P2/1s2s4/2np2ppp/1pPkN2+b1/P2NS+b3/1P1+s2P1P/4PK+R2/3g3+lL w N5Pglp 3')
xxx = board.mate_move_in_1ply()
print(cshogi.move_to_usi(xxx))
→　2e5h (本来ならNoneと帰ってくるはず)

**Comment by TadaoYamaoka** [comment]
説明を書いていないのが良くないのですが、mate_move_in_1plyは高速1手詰めルーチンになっていまして、王手チェックは行っておらず、遠隔からの王手も生成していません。

**Comment by Yasuyuki-Miura** [comment]
そういうことでしたか。
了解いたしました。ご説明いただきありがとうございます。
