### ISSUE TITLE
cshogi.cliで--openingオプションをつけると反則手を指す

### ISSUE THREAD

**Issue by penguinyamap** [TadaoYamaoka/cshogi#28]
[colab](https://colab.research.google.com/drive/1XZ8fkaMfh7T0R1SKhYzMZIAWd6vJnkmR?usp=sharing)
上記のコラボのような問題が発生しています。
既に26の歩を突いている局面から対局を始めようとしても、エンジンがその局面を認識できておらずに、無理やり26歩を指そうとして反則になっているように思えます。

**Comment by TadaoYamaoka** [comment]
フォーマットは、
```
startpos moves 2g2f 8c8d
```
のようになっているでしょうか？

この互角局面集は機能しています。
https://gist.github.com/TadaoYamaoka/41a09638fcf07145101e1c716978fb76

**Comment by penguinyamap** [comment]
`position startpos moves 7g7f 8c8d 7i6h 3c3d 6h7g 7a6b 2g2f 7c7d 2f2e 4a3b 3i4h 6c6d 3g3f 6b6c 6i7h 8a7c`

のような感じで不要な文字を入れてました。positionを消したら正常に動作しました。ご迷惑をおかけしました。
