### ISSUE TITLE
自玉王手時の王手放置一手詰め判定バグ

### ISSUE THREAD

**Issue by JeanWaterCastle** [TadaoYamaoka/cshogi#33]
自玉が王手されている際に「mate_move_in_1ply」を使用すると、王手放置で一手詰め（反則手）の着手を返すようです。

例：
position sfen rrll1pppp/llbgggg2/ppppssssK/2n1p4/3nkn3/5n3/B8/9/9 b 9p 1 moves 9g8h
go
bestmove 3b2b

**Comment by TadaoYamaoka** [comment]
#21と同じになりますが、
説明を書いていないのが良くないのですが、mate_move_in_1plyは高速1手詰めルーチンになっていまして、王手チェックは行っておらず、遠隔からの王手も生成していません。
