### ISSUE TITLE
CSA.Parserのバグ

### ISSUE THREAD

**Issue by nagailong** [TadaoYamaoka/cshogi#38]
CSA.Parser.parse_csa()の持ち駒の処理にバグがあるように思えます。
具体的な箇所は、cshogi/src/parser.h の311行目のwhile(true)文です。
このwhile文の最後で index += 2; した上で、while( line.length() > index) などとする必要があると思います。
どうかご確認下さい。

**Comment by TadaoYamaoka** [comment]
v0.6.6で修正しました。
