### ISSUE TITLE
Parserのバグ（同種の持ち駒複数の場合のto_sfen()）

### ISSUE THREAD

**Issue by nagailong** [TadaoYamaoka/cshogi#43]
CSA.Parser.parse_csa()の持ち駒の処理にまた別のバグがあるように思えます。
同種の持ち駒が複数枚ある時、sfen形式では枚数の後に駒種を書き表しますが、逆になっています。

具体的な箇所は、cshogi/src/parser.h の430～433行目です。
430行目で持ち駒の駒種の処理をしていますが、
これは431～433行目の枚数の処理の後にすべきだと思います。

ご確認の上、修正頂けますと幸いです。

**Comment by TadaoYamaoka** [comment]
v0.7.6で修正しました。
