### ISSUE TITLE
Crashes when I build by myself

### ISSUE THREAD

**Issue by ttcwws** [TadaoYamaoka/cshogi#44]
There is no setup.py in the downloaded codes.
So I tried to build it by myself, but it crashes when I tried to call set_pieces with an array without the black king.
I think it is weird because it works when removing the white king.
So I guess it might be the setup problem. Can you provide the setup.py file for compiling the _cshogi.pyx?
Thanks.

**Comment by TadaoYamaoka** [comment]
Added setup.py in v0.8.0
