### ISSUE TITLE
mateMoveInEvenPly() のバグ

### ISSUE THREAD

**Issue by Lefu777** [TadaoYamaoka/cshogi#46]
mate.cpp のmateMoveInEvenPly(Position&, const int) に、

        else if (depth == 2) {
            // 1手詰めかどうか
            if (!pos.mateMoveIn1Ply()) {
                // 1手詰めでない場合
                // 詰みが見つからなかった時点で終了
                pos.undoMove(ml.move);
                return false;
            }
        }

とありますが、以下のようにif(){} の前に王手のcheck を挟む必要があるような気がしています。

        else if (depth == 2) {
		if (givesCheck) {
			pos.undoMove(ml.move);
			return false;    // 不詰みとみなす
		}

            // 1手詰めかどうか
            if (!pos.mateMoveIn1Ply()) {
                // 1手詰めでない場合
                // 詰みが見つからなかった時点で終了
                pos.undoMove(ml.move);
                return false;
            }
        }

**Comment by TadaoYamaoka** [comment]
ソースのコメントに記載している通り、mateMoveInEvenPlyは高速化のため、手番側が王手されていることを呼び出し元で保証していることが前提になっています。

**Comment by Lefu777** [comment]
ありがとうございます。

見つけたのが数か月前なので若干記憶があやふやですが、
このposition::mateMoveIn1Ply() は、王手されている手番がEvasionを指した局面で呼び出されており、
このEvasionにより王手がかかる(givesCheck==true)場合があり、それを確認しないといけない気がしています。

**Comment by Lefu777** [comment]
ありがとうございます。

確かに、厳密にするのであれば、そのような修正方法が望ましいと思います。
然し、そのように修正してしまうと、停止条件にdepthに関するものが含まれていないため、depthが負になっても探索が終了せず、無駄な探索が入る場合があると思います。

実際に、手元の環境では以下の局面で無限再帰っぽい挙動になりました。
(組み合わせ爆発しているだけかもしれません。)

+pbs1B1sll/+p+prg2g1k/pppppp1n1/6pN1/7N1/9/PPPPPPP2/7RK/L2G1GS1L w SNp 1

なので、
	const CheckInfo ci(pos);
	MovePicker<false, false> move_picker(pos);

	if (depth == 0) {
		if (move_picker.size()) return false;    // 逃げられる。
		return true;    // もう手が無い
	}

	for (const auto& ml : move_picker) {
		// 略
	}
のようにすべきだと思います。

**Comment by TadaoYamaoka** [comment]
> 実際に、手元の環境では以下の局面で無限再帰っぽい挙動になりました。
こちらは再現できなかったですが、depthが負になる可能性はご指摘の通りあります。

depth==4で呼び出している3手詰めでも逆王手は不詰みにしていたので、それに合わせて初めにご提示いただいた修正内容で修正することにしました(v0.8.3で対応)。
