### ISSUE TITLE
documentの修正について

### ISSUE THREAD

**Issue by nawta** [TadaoYamaoka/cshogi#47]
以下のドキュメントの2点の返り値はstr型ではなくbytes型であるように思われます（画像参照）
https://tadaoyamaoka.github.io/cshogi/cshogi.html#cshogi.to_usi
https://tadaoyamaoka.github.io/cshogi/cshogi.html#cshogi.to_csa
<img width="457" alt="スクリーンショット 2024-01-15 1 28 09" src="https://github.com/TadaoYamaoka/cshogi/assets/39507181/ea77bd38-791f-453c-aeeb-3cd46130fc5d">

**Comment by TadaoYamaoka** [comment]
修正しました。

なお、strの戻り値が欲しい場合は、move_to_usiとmove_to_csaを使用してください。
