### ISSUE TITLE
RuntimeError: incorrect move string

### ISSUE THREAD

**Issue by KShunji** [TadaoYamaoka/cshogi#51]
Python 3.11+cshogi 0.8.5

import cshogi
board = cshogi.Board()
board.set_position('sfen 4+Rrkn1/4S4/6+S2/4gppp1/4N4/9/9/9/9 b L2b3g2s2n3l15p 1 moves 5a4b')

上記コードがRuntimeErrorを送出します。
board.set_position('sfen 4+Rrkn1/4S4/6+S2/4gppp1/4N4/9/9/9/9 b L2b3g2s2n3l15p 1)
とした時、board.legal_movesには'5a4b'の数値の指し手は含まれておらず、
board.push_usi('5a4b')は0を返します。

**Comment by TadaoYamaoka** [comment]
現状は、玉が駒箱に入っている局面はサポートしていません。
適当な位置に玉を配置していただく必要があります。

**Comment by KShunji** [comment]
迅速なご回答ありがとうございます。
承知しました。
