### ISSUE TITLE
自己対局を後手番から始めると、エンジンが表記と逆になる

### ISSUE THREAD

**Issue by komafont** [TadaoYamaoka/cshogi#8]
cshogi.cli.main() にて、
初期局面でmovesが奇数個指定されるなどして後手番から対局を開始すると、後手番をengines_order[0]が指すことになるため、記録される対局者名と実際に指したエンジンが逆になるのではないでしょうか？

`while not is_game_over:`
`    for engine, listener, byoyomi in zip(engines_order, listeners_order, byoyomi_order):`

**Comment by TadaoYamaoka** [comment]
ご指摘ありがとうございます。
バグでしたので修正いたしました。

**Comment by komafont** [comment]
ご対応いただき、ありがとうございました。
