### ISSUE TITLE
Visual Studio以外の環境でのビルド

### ISSUE THREAD

**Issue by youyou-ku** [TadaoYamaoka/cshogi#9]
初歩的な質問で申し訳ないのですが、cshogiはVisualStudio以外の環境、例えばUbuntu上でpython3 setup.py buildなどとすればビルドできるのでしょうか。Ubuntu上で動かせるようにしたいのですがビルド方法が分からなかったので教えていただけるとありがたいです。

**Comment by TadaoYamaoka** [comment]
Cythonを使用していますので、gitからcloneした場合は、pip install -e .で自動的にビルドしてインストールできます。
Ubuntuにg++がインストールされている必要があります。
apt install build-essential
でインストールしておけばよいです。
numpyとCythonが依存関係になっているので、
pip install numpy Cython
も必要です。

個別にビルドしなくても、PYPIに登録していますので、
pip install cshogi
でビルド済みのパッケージがUbuntuにもインストールできます。

**Comment by youyou-ku** [comment]
ありがとうございます！助かりました
